name: Gtb test all
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Cache gradle dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build with Gradle
        run: |
          cat settings.gradle | grep 'rootProject.name' > settings.gradle.bak
          mv settings.gradle.bak settings.gradle
          ./gradlew clean build test
      - if: ${{ success() }}
        run: echo "TEST_RESULT=true" >> $GITHUB_ENV
      - if: ${{ failure() }}
        run: echo "TEST_RESULT=false" >> $GITHUB_ENV
      - if: ${{ always() }}
        run: |
          PROJECT_NAME=$(echo ${{ github.repository }} | cut -d/ -f2)
          curl -X POST "${{ secrets.DASHBOARD_ADDRESS }}/terms/${{ secrets.STUDENT_TERM }}/submissions/test?assignmentKey=${PROJECT_NAME}&gtbUsername=${{ secrets.STUDENT_NAME }}" \
              -H "Content-Type: application/json" \
              -u user:${{ secrets.SONAR_TOKEN }} \
              -d "${TEST_RESULT}"


